kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    nodepool: vendor
- role: worker
  labels:
    nodepool: vendor
- role: worker
  labels:
    nodepool: acme
- role: worker
  labels:
    nodepool: acme
