apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: ops
  source:
    chart: sealed-secrets
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.2.11
    helm:
      releaseName: sealed-secrets
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
